sudo: required
services:
  - docker

before_install:
  - docker build -t thamastermind/docker-react-1 -f Dockerfile.dev .

script:
  - docker run thamastermind/docker-react-1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-734068183928"
  bucket_path: "DockerReact1"
  on:
    branch: master
  access_key_id: $AWS Access key ID
  secret_access_key:
    secure: $AWS Secret Access Key

