sudo: required
services:
  - docker

before_install:
  - docker build -t thamastermind/docker-react-1 -f Dockerfile.dev .

script:
  - docker run thamastermind/docker-react-1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: AKIAINC3OXM5YIZRAGSQ
  secret_access_key:
    secure: "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"

